name: Automated E2E Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: run cypress tests with Electron
        uses: cypress-io/github-actions@v4
        with:
          browser: electron
