name: Automated Unit Testing
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node_version: 16

      - name: Install All Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-unit
